apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trackableappname" . }}-cron
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
data:
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1YjNlMTU2OWFiOTkzZjAwMTIzNmZiMDgiLCJ0aW1lc3RhbXAiOiIyMDE4LTA3LTA2VDEwOjA1OjM1LjQxOVoiLCJ1c2VyVHlwZSI6IkFkbWluIiwiaWF0IjoxNTMwODcxNTM1fQ.6JwjOsHr9a0bDGOaByvxvGYyhzakAHGWMCZ5f4l734w'
