{{- if .Values.service.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/rewrite-target: /
    kubernetes.io/add-base-url: "true"
spec:
{{ if eq .Values.development.dev false}}
  tls:
  - hosts:
    - {{ template "hostname" .Values.service.url }}
    secretName: {{ template "fullname" . }}-tls
{{ end }}
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path}}
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{ if eq .Values.development.dev false}}
    host: {{ template "hostname" .Values.service.url }}
{{ end }}
{{- end -}}
